[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "energy-audit"
version = "0.1.0"
dependencies = ["psutil"]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
audit = "audit.audit:main"
