services:
  MemoryService:
    command: "python3"
    entrypoint: "tester1_mem.py"
    working_directory: "../codebase/"
    env_vars:
      NODE_ENV: "development"
    shell: true
    background: true
    capture_pid: true

  CPUService:
    command: "python3"
    entrypoint: "tester2_cpu.py"
    working_directory: "../codebase/"
    env_vars:
      BROWSER: "none"
    shell: true
    background: true
    capture_pid: true
